name: Deploy App to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build the project
      - name: Build
        run: npm run build

      # 5️⃣ Setup SSH key from secrets (base64 decoded)
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          # Debug: Check if key file exists and has content
          echo "SSH key file size:" $(wc -c ~/.ssh/id_rsa)
          echo "SSH key first line:" $(head -1 ~/.ssh/id_rsa)
          echo "SSH key last line:" $(tail -1 ~/.ssh/id_rsa)

      # 6️⃣ Copy files to VPS (manual SCP)
      - name: Copy files to VPS
        run: |
          # Test SSH connection first
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"
          
          # Create target directory if it doesn't exist
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p /applis/dev/ci-cd"
          
          # Copy files using SCP
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./dist/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/applis/dev/ci-cd/

      # 7️⃣ Deploy on VPS (manual SSH)
      - name: Finalize deployment
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /applis/dev/ci-cd
            npm install --production
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
          EOF