name: Deploy App to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 3️⃣ Build the project
      - name: Build
        run: npm run build

      # 4️⃣ Decode the base64 SSH key
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # 5️⃣ Copy built files to VPS via SCP
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key_path: ~/.ssh/id_rsa
          port: 22
          source: "./dist"
          target: "/applis/dev/ci-cd"
          strip_components: 1

      # 6️⃣ Run commands on VPS via SSH
      - name: Finalize deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key_path: ~/.ssh/id_rsa
          port: 22
          script: |
            cd /applis/dev/ci-cd
            npm run build
            pm2 start ecosystem.config.js
