name: Deploy App to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build


      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.VPS_HOST}}
          username: root
          key: ${{secrets.VPS_SSH_KEY}}
          port: 22
          source: "."
          target: "/applis/dev/ci-cd"
          strip_components: 1

      - name: Finalize deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.VPS_HOST}}
          username: root
          key: ${{secrets.VPS_SSH_KEY}}
          port: 22
          script: |
            cd /applis/dev/ci-cd
            npm run build
            pm2 start ecosystem.config.js

                                    
                                   
