name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code du dépôt dans le répertoire par défaut $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Afficher le répertoire courant pour comprendre où on est
      - name: Show current directory
        run: |
          pwd
          ls -la

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Construire l'application
      - name: Build application
        run: npm run build

      # 5. Préparer le dossier de déploiement sur le VPS
      - name: Prepare deployment directory on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p /var/www/myapp
            echo "VPS directory ready"

      # 6. Envoyer les fichiers sur le VPS
      - name: Upload files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/myapp"
