kind: pipeline
type: docker
name: deploy-app

steps:

  # 1️⃣ Checkout code
  - name: Checkout
    image: alpine/git
    commands:
      - git clone https://github.com/your/repo.git .

  # 2️⃣ Install dependencies
  - name: Install dependencies
    image: node:20
    commands:
      - npm install

  # 3️⃣ Build project
  - name: Build
    image: node:20
    commands:
      - npm run build

  # 4️⃣ Setup SSH key from base64 secret
  - name: Setup SSH key
    image: alpine
    environment:
      VPS_SSH_KEY_B64:
        from_secret: VPS_SSH_KEY_B64
    commands:
      - mkdir -p ~/.ssh
      - echo "$VPS_SSH_KEY_B64" | base64 -d > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

  # 5️⃣ Copy files to VPS
  - name: Copy files
    image: appleboy/drone-scp
    environment:
      VPS_HOST:
        from_secret: VPS_HOST
    settings:
      host: $VPS_HOST
      username: ubuntu
      key: ~/.ssh/id_rsa
      port: 22
      source: ./dist
      target: /applis/dev/ci-cd
      strip_components: 1

  # 6️⃣ Run remote commands via SSH
  - name: Finalize deployment
    image: appleboy/drone-ssh
    environment:
      VPS_HOST:
        from_secret: VPS_HOST
    settings:
      host: $VPS_HOST
