name: Create Dev Directory on VPS

on:
  push:
    branches: [ main ]

jobs:
  setup-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Create dev directory on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 148.230.124.150
          username: root
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXV8tik9FKkRFAThAPlOHYtidSo/qoHBWTYep5s1s91l0AlXdLQD6JLI/03RyB5JQiRhh/NIz9JXVHw4rCDf6X3DP/PNhNbJQL7m4ylex/u+cJbJwLFBosd7rUEbX3kT0GVwFOySs5jzj1R3C3KdU3dH3ItZT4xoPj36XhvzG5V27Ispn41FAu1Q6pKri62PgbUDeK78in9gjCZcxFQThoFob6d40+UB3MYlKIzP14XwzN55MF7gfiEhRV8LQevX4Zo6cHv7muEJv2nFbjZw0LQhx7NSOhUpbhrG25TJEzCPg7UGDYYeTrqW70Fw5wGdnIMbBuXjZFsQbY13io5PsaA1v/iAFsHW3HwjJ5FLs7IY4yDc7fvVr+pc8Vitp+6tV2ZmFl+zyuk0Eucwd2j8zclxxn3N3LAOmLeK2SNhl4ibZf5QxTJHHQ050T/p9x9gaQunNM7n2D3oZe9qejulnZMVuFZ6yyyrr8SwLVnOdyHW8xBIpfiDBRARCj+891nRzy8KN8XtuhKv/JIKcSNVe/yZCHpARvyX0pklMTvOe0nyL3NSFD2zSjHRkxRVJ0+iDu319H/66tWiUffa5dZqmgZ7x2Rspe0O0DlGBt7xCheoeyW0JOpB5NT8NGzZZYrD9gHiiexbfyxfin/FOhM8dQ0T5KEVzCZwdPPhgA3t0D0Q== ahmed@live.fr
          port: 22
          script: |
            # Create /applis/dev directory
            mkdir -p /applis/dev
            
            # Set proper permissions
            chmod 755 /applis/dev
            
            # Verify directory was created
            ls -la /applis/dev
            
            echo "✅ Directory /applis/dev created successfully!"