name: Deploy to VPS

on:
  push:
    branches:
      - main  # Déclenche sur push vers la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installation des dépendances
      - name: Install dependencies
        run: npm install

      # 3. Build de l'application
      - name: Build application
        run: npm run build

      # 4. Envoi des fichiers buildés vers le VPS
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/*" # Chemin local (adapter selon ton projet)
          target: "/var/www/myapp" # Chemin sur le VPS

      # 5. Relancer le service sur le VPS
      - name: Restart application on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/myapp
            pm2 restart myapp || pm2 start dist/index.js --name myapp
