name: Deploy App to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare deployment directory on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            
            
            # Navigate to the directory
            cd /applis/dev/ci-cd
            
            # Create a backup of current version if it exists
            if [ -d "vue-app" ]; then
              mv vue-app vue-app-backup-$(date +%Y%m%d-%H%M%S)
              echo "✅ Backup created"
            fi
            
            # Create new directory for the app
            mkdir -p vue-app
            
            echo "✅ Deployment directory prepared"

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "dist/*"
          target: "/applis/dev"
          strip_components: 1

      - name: Finalize deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /applis/dev/ci-cd
            npm install --verbose
                                 
                                    
                                   
